#pragma once

#include "CoreMinimal.h"
#include "Protocols/SimpleNetProtocols.h"
#include "SimpleProtocolsDefinition.h"

DEFINITION_SIMPLE_PROTOCOLS(C2D_DATA_REQUEST, 100);		/* 测试 获取UGC元素信息请求 {...} */
DEFINITION_SIMPLE_PROTOCOLS(D2C_DATA_RESPONSE, 101);	/* 测试响应 {...} */

DEFINITION_SIMPLE_PROTOCOLS(C2D_UGC_MAP_ELEMENT_INFO_REQUEST, 150);		/* 获取UGC元素信息请求 {int32 MapID} */
DEFINITION_SIMPLE_PROTOCOLS(D2C_UGC_MAP_ELEMENT_INFO_RESPONSE, 151);	/* 获取UGC元素信息响应 {int32 MapID, int32[], float[]} */

DEFINITION_SIMPLE_PROTOCOLS(C2D_UGC_MAP_INFO_REQUEST, 152);		/* 获取UGC所有Map信息请求 {} */
DEFINITION_SIMPLE_PROTOCOLS(D2C_UGC_MAP_INFO_RESPONSE, 153);	/* 获取UGC所有Map信息响应 {FString[], int32[]} */

DEFINITION_SIMPLE_PROTOCOLS(C2D_UGC_SAVE_MAP_INFO_REQ, 154);		/* 保存UGC的Map信息请求 {int32 MapID, int32[], float[]} */
DEFINITION_SIMPLE_PROTOCOLS(D2C_UGC_SAVE_MAP_INFO_REP, 155);	/* 保存UGC的Map信息响应 {} */